### ISSUE TITLE
Progress on getting this to macOS (and BSD, perhaps)?

### ISSUE THREAD

**Issue by barracuda156** [nathan-yan/courier#3]
Hi,

Is something being done re bringing this to Unix-like systems? Would be great to have this app working!

**Comment by barracuda156** [comment]
I am not sure which `ncurses`-based lib it needs on macOS (`windows-curses` looks like a Windows-only one), but otherwise running `messenger.py` fails on this:
```
36-174% /opt/local/bin/python3.11 /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_courier/courier/work/courier-99ef54d23eda18d08812cd9fe0a8017839f39fcd/messenger.py 
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_courier/courier/work/courier-99ef54d23eda18d08812cd9fe0a8017839f39fcd/messenger.py", line 551, in <module>
    wrapper(main)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_courier/courier/work/courier-99ef54d23eda18d08812cd9fe0a8017839f39fcd/messenger.py", line 345, in main
    curses.init_pair(4, 8, curses.COLOR_BLACK)
ValueError: Color number is greater than COLORS-1 (7).
```
